<?php
echo "Server IP address: ".$_SERVER['SERVER_ADDR']."<br>";
echo "Server name: ".$_SERVER['SERVER_NAME']."<br>";
echo "Server software: ".$_SERVER['SERVER_SOFTWARE']."<br>";
echo "Server administrator: ".$_SERVER['SERVER_ADMIN']."<br>";
echo "Server port: ".$_SERVER['SERVER_PORT']."<br>";
echo "Server protocol: ".$_SERVER['SERVER_PROTOCOL']."<br>";
echo "Document root: ".$_SERVER['DOCUMENT_ROOT']."<br>";
echo "Remote IP address: ".$_SERVER['REMOTE_ADDR']."<br>";
echo "Remote port: ".$_SERVER['REMOTE_PORT']."<br>";
echo "Request method: ".$_SERVER['REQUEST_METHOD']."<br>";
echo "Request URI: ".$_SERVER['REQUEST_URI']."<br>";
echo "Script filename: ".$_SERVER['SCRIPT_FILENAME']."<br>";
echo "Script name: ".$_SERVER['SCRIPT_NAME']."<br>";
echo "Query string: ".$_SERVER['QUERY_STRING']."<br>";
echo "HTTP Host: ".$_SERVER['HTTP_HOST']."<br>";
echo "HTTP User Agent: ".$_SERVER['HTTP_USER_AGENT']."<br>";
echo "HTTP Accept: ".$_SERVER['HTTP_ACCEPT']."<br>";
echo "HTTP Accept Language: ".$_SERVER['HTTP_ACCEPT_LANGUAGE']."<br>";
echo "HTTP Accept Encoding: ".$_SERVER['HTTP_ACCEPT_ENCODING']."<br>";
echo "HTTP Connection: ".$_SERVER['HTTP_CONNECTION']."<br>";
echo "HTTP Cache Control: ".$_SERVER['HTTP_CACHE_CONTROL']."<br>";
echo "HTTP Upgrade Insecure Requests: ".$_SERVER['HTTP_UPGRADE_INSECURE_REQUESTS']."<br>";
echo "HTTP Pragma: ".$_SERVER['HTTP_PRAGMA']."<br>";
echo "HTTP Referer: ".$_SERVER['HTTP_REFERER']."<br>";
echo "HTTP Sec Fetch Site: ".$_SERVER['HTTP_SEC_FETCH_SITE']."<br>";
echo "HTTP Sec Fetch Mode: ".$_SERVER['HTTP_SEC_FETCH_MODE']."<br>";
echo "HTTP Sec Fetch User: ".$_SERVER['HTTP_SEC_FETCH_USER']."<br>";
echo "HTTP Sec Fetch Dest: ".$_SERVER['HTTP_SEC_FETCH_DEST']."<br>";
echo "HTTP Accept Charset: ".$_SERVER['HTTP_ACCEPT_CHARSET']."<br>";
echo "HTTP Sec CH UA Platform: ".$_SERVER['HTTP_SEC_CH_UA_PLATFORM']."<br>";
echo "HTTP Sec CH UA: ".$_SERVER['HTTP_SEC_CH_UA']."<br>";
echo "HTTP Sec CH UA Arch: ".$_SERVER['HTTP_SEC_CH_UA_ARCH']."<br>";
echo "HTTP Sec CH UA Mobile: ".$_SERVER['HTTP_SEC_CH_UA_MOBILE']."<br>";
echo "HTTP Sec CH UA Platform Mobile: ".$_SERVER['HTTP_SEC_CH_UA_PLATFORM_MOBILE']."<br>";
echo "HTTP Sec Fetch Site: ".$_SERVER['HTTP_SEC_FETCH_SITE']."<br>";
echo "HTTP Sec Fetch User: ".$_SERVER['HTTP_SEC_FETCH_USER']."<br>";
echo "HTTP Sec Fetch Dest: ".$_SERVER['HTTP_SEC_FETCH_DEST']."<br>";
echo "Server signature: ".$_SERVER['SERVER_SIGNATURE']."<br>";
echo "Server root: ".$_SERVER['SERVER_ROOT']."<br>";
echo "Server software: ".$_SERVER['SERVER_SOFTWARE']."<br>";
echo "Server protocol: ".$_SERVER['SERVER_PROTOCOL']."<br>";
echo "Server admin: ".$_SERVER['SERVER_ADMIN']."<br>";
echo "Server port: ".$_SERVER['SERVER_PORT']."<br>";
echo "Server document root: ".$_SERVER['DOCUMENT_ROOT']."<br>";
echo "Server request scheme: ".$_SERVER['REQUEST_SCHEME']."<br>";
echo "Server context document root: ".$_SERVER['CONTEXT_DOCUMENT_ROOT']."<br>";
echo "Server gateway interface: ".$_SERVER['GATEWAY_INTERFACE']."<br>";
echo "Server protocol version: ".$_SERVER['SERVER_PROTOCOL']."<br>";
echo "Server request time: ".$_SERVER['REQUEST_TIME']."<br>";
echo "Server request time float: ".$_SERVER['REQUEST_TIME_FLOAT']."<br>";
echo "Server timezone: ".$_SERVER['TZ']."<br>";
echo "Server script filename: ".$_SERVER['SCRIPT_FILENAME']."<br>";
echo "Server script name: ".$_SERVER['SCRIPT_NAME']."<br>";
echo "Server script uri: ".$_SERVER['SCRIPT_URI']."<br>";
echo "Server script url: ".$_SERVER['SCRIPT_URL']."<br>";
echo "Server php self: ".$_SERVER['PHP_SELF']."<br>";
echo "Server query string: ".$_SERVER['QUERY_STRING']."<br>";
echo "Server request uri: ".$_SERVER['REQUEST_URI']."<br>";
echo "Server document uri: ".$_SERVER['DOCUMENT_URI']."<br>";
echo "Server php auth digest: ".$_SERVER['PHP_AUTH_DIGEST']."<br>";
echo "Server php auth user: ".$_SERVER['PHP_AUTH_USER']."<br>";
echo "Server php auth pw: ".$_SERVER['PHP_AUTH_PW']."<br>";
echo "Server auth type: ".$_SERVER['AUTH_TYPE']."<br>";
echo "Server path info: ".$_SERVER['PATH_INFO']."<br>";
echo "Server orig path info: ".$_SERVER['ORIG_PATH_INFO']."<br>";
echo "Server http cookie: ".$_SERVER['HTTP_COOKIE']."<br>";
echo "Server http accept: ".$_SERVER['HTTP_ACCEPT']."<br>";
echo "Server http accept charset: ".$_SERVER['HTTP_ACCEPT_CHARSET']."<br>";
echo "Server http accept encoding: ".$_SERVER['HTTP_ACCEPT_ENCODING']."<br>";
echo "Server http accept language: ".$_SERVER['HTTP_ACCEPT_LANGUAGE']."<br>";
echo "Server http connection: ".$_SERVER['HTTP_CONNECTION']."<br>";
echo "Server http host: ".$_SERVER['HTTP_HOST']."<br>";
echo "Server http referer: ".$_SERVER['HTTP_REFERER']."<br>";
echo "Server http user agent: ".$_SERVER['HTTP_USER_AGENT']."<br>";
echo "Server http x forwarded for: ".$_SERVER['HTTP_X_FORWARDED_FOR']."<br>";
echo "Server http x forwarded host: ".$_SERVER['HTTP_X_FORWARDED_HOST']."<br>";
echo "Server http x forwarded proto: ".$_SERVER['HTTP_X_FORWARDED_PROTO']."<br>";
echo "Server http x forwarded server: ".$_SERVER['HTTP_X_FORWARDED_SERVER']."<br>";
echo "Server remote addr: ".$_SERVER['REMOTE_ADDR']."<br>";
echo "Server remote host: ".$_SERVER['REMOTE_HOST']."<br>";
echo "Server remote port: ".$_SERVER['REMOTE_PORT']."<br>";
echo "Server remote user: ".$_SERVER['REMOTE_USER']."<br>";
echo "Server redirect remote user: ".$_SERVER['REDIRECT_REMOTE_USER']."<br>";
echo "Server auth type: ".$_SERVER['AUTH_TYPE']."<br>";
echo "Server path translated: ".$_SERVER['PATH_TRANSLATED']."<br>";
echo "Server request method: ".$_SERVER['REQUEST_METHOD']."<br>";
echo "Server request scheme: ".$_SERVER['REQUEST_SCHEME']."<br>";
echo "Server request time: ".$_SERVER['REQUEST_TIME']."<br>";
echo "Server request time float: ".$_SERVER['REQUEST_TIME_FLOAT']."<br>";
echo "Server request query string: ".$_SERVER['QUERY_STRING']."<br>";
echo "Server request document root: ".$_SERVER['DOCUMENT_ROOT']."<br>";
echo "Server request uri: ".$_SERVER['REQUEST_URI']."<br>";
echo "Server request script filename: ".$_SERVER['SCRIPT_FILENAME']."<br>";
echo "Server request script name: ".$_SERVER['SCRIPT_NAME']."<br>";
echo "Server request php self: ".$_SERVER['PHP_SELF']."<br>";
echo "Server request argv: ".$_SERVER['argv']."<br>";
echo "Server request argc: ".$_SERVER['argc']."<br>";
phpinfo();
?>
