<?php
echo "Server IP address: ".$_SERVER['SERVER_ADDR']."<br>";
echo "Server name: ".$_SERVER['SERVER_NAME']."<br>";
echo "Server software: ".$_SERVER['SERVER_SOFTWARE']."<br>";
echo "Server administrator: ".$_SERVER['SERVER_ADMIN']."<br>";
echo "Server port: ".$_SERVER['SERVER_PORT']."<br>";
echo "Server protocol: ".$_SERVER['SERVER_PROTOCOL']."<br>";
echo "Document root: ".$_SERVER['DOCUMENT_ROOT']."<br>";
echo "Remote IP address: ".$_SERVER['REMOTE_ADDR']."<br>";
echo "Remote port: ".$_SERVER['REMOTE_PORT']."<br>";
echo "Request method: ".$_SERVER['REQUEST_METHOD']."<br>";
echo "Request URI: ".$_SERVER['REQUEST_URI']."<br>";
echo "Script filename: ".$_SERVER['SCRIPT_FILENAME']."<br>";
echo "Script name: ".$_SERVER['SCRIPT_NAME']."<br>";
echo "Query string: ".$_SERVER['QUERY_STRING']."<br>";
echo "HTTP Host: ".$_SERVER['HTTP_HOST']."<br>";
echo "HTTP User Agent: ".$_SERVER['HTTP_USER_AGENT']."<br>";
echo "HTTP Accept: ".$_SERVER['HTTP_ACCEPT']."<br>";
echo "HTTP Accept Language: ".$_SERVER['HTTP_ACCEPT_LANGUAGE']."<br>";
echo "HTTP Accept Encoding: ".$_SERVER['HTTP_ACCEPT_ENCODING']."<br>";
echo "HTTP Connection: ".$_SERVER['HTTP_CONNECTION']."<br>";
echo "HTTP Cache Control: ".$_SERVER['HTTP_CACHE_CONTROL']."<br>";
echo "HTTP Upgrade Insecure Requests: ".$_SERVER['HTTP_UPGRADE_INSECURE_REQUESTS']."<br>";
echo "HTTP Pragma: ".$_SERVER['HTTP_PRAGMA']."<br>";
echo "HTTP Referer: ".$_SERVER['HTTP_REFERER']."<br>";
echo "HTTP Sec Fetch Site: ".$_SERVER['HTTP_SEC_FETCH_SITE']."<br>";
echo "HTTP Sec Fetch Mode: ".$_SERVER['HTTP_SEC_FETCH_MODE']."<br>";
echo "HTTP Sec Fetch User: ".$_SERVER['HTTP_SEC_FETCH_USER']."<br>";
echo "HTTP Sec Fetch Dest: ".$_SERVER['HTTP_SEC_FETCH_DEST']."<br>";
echo "HTTP Accept Charset: ".$_SERVER['HTTP_ACCEPT_CHARSET']."<br>";
echo "HTTP Sec CH UA Platform: ".$_SERVER['HTTP_SEC_CH_UA_PLATFORM']."<br>";
echo "HTTP Sec CH UA: ".$_SERVER['HTTP_SEC_CH_UA']."<br>";
echo "HTTP Sec CH UA Arch: ".$_SERVER['HTTP_SEC_CH_UA_ARCH']."<br>";
echo "HTTP Sec CH UA Mobile: ".$_SERVER['HTTP_SEC_CH_UA_MOBILE']."<br>";
echo "HTTP Sec CH UA Platform Mobile: ".$_SERVER['HTTP_SEC_CH_UA_PLATFORM_MOBILE']."<br>";
echo "HTTP Sec Fetch Site: ".$_SERVER['HTTP_SEC_FETCH_SITE']."<br>";
echo "HTTP Sec Fetch User: ".$_SERVER['HTTP_SEC_FETCH_USER']."<br>";
echo "HTTP Sec Fetch Dest: ".$_SERVER['HTTP_SEC_FETCH_DEST']."<br>";
phpinfo();
?>
